[tool.poetry]
name = "blog-notebooks"
version = "0.1.0"
description = ""
authors = ["joypauls <joypaulsen3@gmail.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = ">=3.13"
numpy = "^1.26.0"
pyqt6 = "^6.5.2"
opencv-python = "^4.8.1.78"
matplotlib = "^3.8.4"
scipy = "^1.14.1"


[tool.poetry.group.dev.dependencies]
ipykernel = "^6.29.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
